### Steps involved in constructing a basic XOR gate using Neural network

- Initialize the weights and biases randomly.
- Compute the predicted output using the sigmoid function
- Compute the loss using the square error loss fucntion 
- Update the weights and biases after computing the error by
  W(new) = W(old) - α*∆W, 
  B(new) = B(old) — α*∆B
- Repeat the entire process (i.e forward and backward propagation) until the error is minimum.

In [8]:
import numpy as np

In [9]:
#Declare the weights

inputs = np.array([[0,0], [0,1], [1,0], [1,1]])
expected_output = np.array([[0], [1], [1], [0]])

In [10]:
#Initialize the weights with random values 

inputLayerNeurons, hiddenLayerNeurons, outputLayerNeurons = 2,2,1

hidden_weights = np.random.uniform(size=(inputLayerNeurons, hiddenLayerNeurons))
hidden_bias =np.random.uniform(size=(1, hiddenLayerNeurons))

output_weights = np.random.uniform(size=(hiddenLayerNeurons, outputLayerNeurons))
output_bias = np.random.uniform(size=(1, outputLayerNeurons))

In [11]:
hidden_weights, hidden_bias, output_weights, output_bias

(array([[0.91222677, 0.09789826],
        [0.76273039, 0.87692956]]),
 array([[0.37462675, 0.18071997]]),
 array([[0.76756455],
        [0.38030312]]),
 array([[0.22573093]]))

In [12]:
#Forward propagation

def forward_prop():
    def sigmoid (x):
        return 1/(1 + np.exp(-x))
    
    hidden_layer_activation = np.dot(inputs,hidden_weights)
    hidden_layer_activation += hidden_bias

    hidden_layer_output = sigmoid(hidden_layer_activation)

    output_layer_activation = np.dot(hidden_layer_output,output_weights)
    output_layer_activation += output_bias

    predicted_output = sigmoid(output_layer_activation)
    
    return hidden_layer_output, predicted_output
    

In [15]:
#Backpropagation
epochs = 1000000
for i in range(epochs):  
    
    hidden_layer_output, predicted_output = forward_prop()
    
    def sigmoid_derivative(x):
        return x * (1 - x)

    lr = 0.1
    
    error = expected_output - predicted_output
    d_predicted_output = error * sigmoid_derivative(predicted_output)
 
    error_hidden_layer = d_predicted_output.dot(output_weights.T)
    d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_output)

    #Updating Weights and Biases
    
    output_weights += hidden_layer_output.T.dot(d_predicted_output) * lr
    output_bias += np.sum(d_predicted_output,axis=0,keepdims=True) * lr
    hidden_weights += inputs.T.dot(d_hidden_layer) * lr
    hidden_bias += np.sum(d_hidden_layer,axis=0,keepdims=True) * lr
    

In [17]:
#XOR gate output

predicted_output

array([[0.00392744],
       [0.99670457],
       [0.99669991],
       [0.00335329]])