In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
import re
from textblob import TextBlob
from nltk.corpus import stopwords 
from sklearn import model_selection, preprocessing, naive_bayes, metrics
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn import decomposition, ensemble
import string
from sklearn.externals import joblib
from sklearn import svm

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


In [2]:
df = pd.read_csv("data.csv")

In [3]:
df.head()

Intents     Text
0  Greetings       Hi
1  Greetings    Hello
2  Greetings      Hey
3  Greetings      Hai
4  Greetings  whatsup

In [4]:
df['Intents'].unique().size

22

In [5]:
label_encoder = preprocessing.LabelEncoder()
df['Intents'] = label_encoder.fit_transform(df['Intents'])
df['Intents'].unique()

array([ 8, 17, 11, 15, 16, 18, 21, 19, 20,  6, 12, 13,  4,  5, 14,  9,  0,
        1,  3, 10,  2,  7])

In [6]:
df.head()

Intents     Text
0        8       Hi
1        8    Hello
2        8      Hey
3        8      Hai
4        8  whatsup

In [7]:
#splitting the dataset into training and validation datasets
train_x, test_x, train_y, test_y = model_selection.train_test_split(df["Intents"], df["Text"], random_state = 42, test_size = 0.2)

In [8]:
count_vect = CountVectorizer()
count_vect.fit(df["Text"])

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [9]:
#transform the training and validation data using count vectorizer object 
ytrain_count = count_vect.transform(train_y)
ytest_count = count_vect.transform(test_y)

In [10]:
model_nb = naive_bayes.MultinomialNB().fit(ytrain_count, train_x) 

In [11]:
model_svm = svm.LinearSVC().fit(ytrain_count, train_x) 

In [12]:
model_nb

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [13]:
model_svm

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

In [30]:
predictions_nb = model_nb.predict(ytest_count)

In [31]:
predictions_svm = model_svm.predict(ytest_count)

In [32]:
predictions_nb

array([13, 14, 11, 17, 14, 13,  4, 17, 10, 17, 17, 18, 17,  9,  9, 13, 17,
       10, 17,  0, 13, 14, 13,  9, 12,  9, 11, 17, 14])

In [33]:
predictions_svm

array([13, 14, 11, 19, 14, 18,  4,  9, 10, 17, 11, 18, 17,  9,  9,  8, 11,
       10, 17,  0, 13, 14,  0,  9, 12,  8,  6, 18, 14])

In [34]:
# Naive bayes
f1_score_nb = metrics.f1_score(predictions_nb, test_x, average = 'micro')
accuracy_nb = metrics.accuracy_score(predictions_nb, test_x)

In [35]:
# SVM
f1_score_svm = metrics.f1_score(predictions_svm, test_x, average = 'micro')
accuracy_svm = metrics.accuracy_score(predictions_svm, test_x)

In [36]:
accuracy_nb, f1_score_nb

(0.6206896551724138, 0.6206896551724138)

In [37]:
accuracy_svm, f1_score_svm

(0.896551724137931, 0.896551724137931)

In [26]:
a = np.zeros((5,1))

In [42]:
a

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])