In [2]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
import re
from textblob import TextBlob
from nltk.corpus import stopwords 
from sklearn import model_selection, preprocessing, naive_bayes, metrics
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn import decomposition, ensemble
import string
from sklearn.externals import joblib
from sklearn import svm

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


In [5]:
df = pd.read_csv("data.csv")

In [7]:
df.head()

Intents     Text
0  Greetings       Hi
1  Greetings    Hello
2  Greetings      Hey
3  Greetings      Hai
4  Greetings  whatsup

In [9]:
df.head()

Intents     Text
0        8       Hi
1        8    Hello
2        8      Hey
3        8      Hai
4        8  whatsup

In [35]:
df_train = pd.read_csv("train_data.csv")
df_test = pd.read_csv("test_data.csv")

In [36]:
label_encoder = preprocessing.LabelEncoder()
df_train['Intents'] = label_encoder.fit_transform(df_train['Intents'])
df_train['Intents'].unique()

array([ 7, 16, 10, 14, 15, 17, 20, 18, 19,  6, 11, 12,  4,  5, 13,  8,  0,
        1,  3,  9,  2])

In [37]:
df_test['Intents'] = label_encoder.fit_transform(df_test['Intents'])
df_test['Intents'].unique()

array([ 7, 16, 10, 14, 15, 17, 20, 18, 19,  6, 11, 12,  4,  5, 13,  8,  0,
        1,  3,  9,  2])

In [38]:
count_vect = CountVectorizer()
count_vect.fit(df_train["Text"])
count_vect.fit(df_test["Text"])

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [39]:
#transform the training and validation data using count vectorizer object 
ytrain_count = count_vect.transform(df_train["Text"])
ytest_count = count_vect.transform(df_test["Text"])

In [40]:
#for Naive Bayes
model_nb = naive_bayes.MultinomialNB().fit(ytrain_count, df_train["Intents"]) 

#for SVM
model_svm = svm.LinearSVC().fit(ytrain_count, df_train["Intents"]) 

In [41]:
model_nb, model_svm

(MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True),
 LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
           intercept_scaling=1, loss='squared_hinge', max_iter=1000,
           multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
           verbose=0))

In [42]:
predictions_nb = model_nb.predict(ytest_count)
predictions_svm = model_svm.predict(ytest_count)
predictions_nb, predictions_svm

(array([ 8,  8, 16, 16, 10, 10, 10, 15, 15, 16, 17, 17, 18, 16, 16, 13, 13,
        11, 11, 12, 12,  4, 12,  8, 13, 13,  8,  8,  8,  0,  1,  8, 12,  9,
         9,  2]),
 array([ 7,  7, 16, 16, 10, 10, 14, 15, 15, 17, 17, 17, 18, 16, 19, 13, 13,
        11, 11, 12, 12,  4,  4,  5, 13, 13,  8,  8,  3,  0,  1,  7,  3,  9,
         9,  2]))

In [43]:
# Naive bayes
f1_score_nb = metrics.f1_score(predictions_nb, df_test["Intents"], average = 'micro')
accuracy_nb = metrics.accuracy_score(predictions_nb, df_test["Intents"])

In [44]:
f1_score_nb, accuracy_nb

(0.6111111111111112, 0.6111111111111112)

In [45]:
# SVM
f1_score_svm = metrics.f1_score(predictions_svm, df_test["Intents"], average = 'micro')
accuracy_svm = metrics.accuracy_score(predictions_svm, df_test["Intents"])

In [47]:
f1_score_svm, accuracy_svm


(0.8333333333333334, 0.8333333333333334)